package net.euler;

/**
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
 * <p/>
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * <p/>
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
 * <p/>
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
 *
 * @author Kevin Crosby
 */
public class P044 {
  private static Primes primes = Primes.getInstance();

  private static int pentagonal(int n) {
    return n * (3 * n - 1) / 2;
  }

  private static boolean isPentagonal(int x) {
    int y = 24 * x + 1;
    return primes.isPerfectSquare(y) && MathUtils.sqrt(y) % 6 == 5;
  }

  public static void main(String[] args) {
    boolean loop = true;
    int d = 0;
    for (int k = 1; loop; k++) {
      int pk = pentagonal(k);
      for (int j = 1; j < k; j++) {
        int pj = pentagonal(j);
        if (isPentagonal(pk - pj) && isPentagonal(pk + pj)) {
          loop = false;
          System.out.println("Found P" + k + " and P" + j + " pentagonal numbers.");
          d = pk - pj;
          break;
        }
      }
    }
    System.out.println("The pair of pentagonal numbers, Pj and Pk");
    System.out.println("for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised;");
    System.out.println("the value of D is " + d);
  }
}
